<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<?php
 // module/Album/view/album/album/index.phtml:

 $title = 'Ksiegarnia internetowa';
 $this->headTitle($title);
 ?>
 <script>
//    $( window ).load(function(){
//        $("#audio").button("toggle");
//        
//        event.preventDefault();
//    });
//    
//    $("button").click(function () {
//    $(this).toggleClass("active");
//});

$( document ).ready(function() {
    //var button-id;
    $(".btn").first().toggleClass("active");
    $(".btn").click(function(){
        $('.btn').removeClass('active');
        $(this).toggleClass('active');
//        button-id = $(this);
//        if(button-id == 'button-01')
    });
});

//$.ajax({
//            type:"POST",
//            // URL : / name of the controller for the site / name of the action to be                         
//            //                                                 executed
//            url:"/example/answer",
//            data:myData,
//            success: function(data){
//                                   //The callback function, that is going to be executed 
//                                   //after the server response. data is the data returned
//                                   //from the server.
//
//                                   // Show the returned text
//                                   $("#answer").text(data.text);
//
//
//                                    },
//            failure(function(){alert("Failure!!");})
//
//
//           });
 </script>
 
 <div class="row" style="border-bottom: 2px solid black;">
    <div class="col-lg-4">
        <h3 style="font-weight: bold; font-stretch: ultra-expanded; margin-bottom: 0px;"><?php echo $this->escapeHtml($title); ?></h3>
        <p style="font-weight: bold; color: #999;">Nasze sklepy prowadzimy z pasja!</p>
    </div>
     <div class="col-lg-4">
         
     </div>
     
     <div class="col-lg-4">
         
     </div>
 </div>

 <div class="row">
     <div class="col-lg-12">
         <h5 style="font-weight: 800; margin-bottom: 20px; margin-top: 20px;">Katalog ksiazek</h5>
     </div>
 </div>

 <div class="row" id="table-00">
     
         <div class="btn-group btn-group-justified" role="group" aria-label="...">
             <div class="btn-group" role="group" aria-label="label">
                 <button type="button" class="btn btn-default btn-sm" id="button-00">Wszystkie</button>
             </div>
             <div class="btn-group" role="group" aria-label="label">
                 <button type="button" class="btn btn-default btn-sm" id="button-01">Audiobooki</button>
             </div>
             <div class="btn-group" role="group" aria-label="label">
                 <button type="button" class="btn btn-default btn-sm" id="button-02">E-booki</button>
             </div>
             <div class="btn-group" role="group" aria-label="label">
                 <button type="button" class="btn btn-default btn-sm" id="button-03">Nowosci</button>
             </div>
             <div class="btn-group" role="group" aria-label="label">
                 <button type="button" class="btn btn-default btn-sm" id="button-04">Zapowiedzi</button>
             </div>
             <div class="btn-group" role="group" aria-label="label">
                 <button type="button" class="btn btn-default btn-sm" id="button-05">Super okazje</button>
             </div>
         </div>
 </div>
 <div class="row" id="table-00">
         <table class="tabela">
     
 <tr class="naglowek">
     <th class="kolumna column-01">Name</th>
     <th class="kolumna column-02">Publish date</th>
     <th class="kolumna column-03">Price</th>
     <th class="kolumna column-04">Autor</th>
     <th class="kolumna column-05">Publisher</th>
     <th class="kolumna column-06">&nbsp;</th>
 </tr>
 <div id="input">
 <?php foreach ($future as $album) : ?>
 <tr>
     <td class="kolumna"><?php echo $this->escapeHtml($album->nazwa);?></td>
     <td class="kolumna"><?php echo $this->escapeHtml($album->data);?></td>
     <td class="kolumna"><?php echo $this->escapeHtml($album->cena);?></td>
     <td class="kolumna"><?php echo $this->escapeHtml($album->autor);?></td>
     <td class="kolumna"><?php echo $this->escapeHtml($album->wydawnictwo);?></td>
     <td class="kolumna">
         <a href="<?php echo $this->url('album',
             array('action'=>'edit', 'id' => $album->id));?>">Edit</a>
         
     </td>
 </tr>
 <?php endforeach; ?>
 </div>
 </table>
     
 </div>

<!-- <div class="btn-group" role="group" aria-label="...">
     <button type="button" class="btn btn-default">Left</button>
     <button type="button" class="btn btn-default">Middle</button>
     <button type="button" class="btn btn-default">Right</button>
 </div>-->
<!-- <p>
     <a href=" <?php //echo $this->url('album', array('action'=>'add'));?>">Add new album</a>
 </p>-->

 
    