<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<?php
 // module/Album/view/album/album/index.phtml:

 $title = 'Ksiegarnia internetowa';
 $this->headTitle($title);
 ?>
 <div class="row" style="border-bottom: 2px solid black;">
    <div class="col-lg-4">
        <h3 style="font-weight: bold; font-stretch: ultra-expanded; margin-bottom: 0px;"><?php echo $this->escapeHtml($title); ?></h3>
        <p style="font-weight: bold; color: #999;">Nasze sklepy prowadzimy z pasja!</p>
    </div>
     <div class="col-lg-4">
         
     </div>
     
     <div class="col-lg-4">
         
     </div>
 </div>

 <div class="row">
     <div class="col-lg-12">
         <h5 style="font-weight: 800; margin-bottom: 20px; margin-top: 20px;">Katalog ksiazek</h5>
     </div>
 </div>

 <div class="row" >
     <div class="col-lg-12">
         <div class="btn-group btn-group-justified" role="group" aria-label="...">
             <div class="btn-group" rol="group" aria-label="label">
                 <button type="button" class="btn btn-default btn-sm">Wszystkie</button>
             </div>
             <div class="btn-group" rol="group" aria-label="label">
                 <button type="button" class="btn btn-default btn-sm">Audiobooki</button>
             </div>
             <div class="btn-group" rol="group" aria-label="label">
                 <button type="button" class="btn btn-default btn-sm">E-booki</button>
             </div>
             <div class="btn-group" rol="group" aria-label="label">
                 <button type="button" class="btn btn-default btn-sm">Nowosci</button>
             </div>
             <div class="btn-group" rol="group" aria-label="label">
                 <button type="button" class="btn btn-default btn-sm">Zapowiedzi</button>
             </div>
             <div class="btn-group" rol="group" aria-label="label">
                 <button type="button" class="btn btn-default btn-sm">Super okazje</button>
             </div>
         </div>
     </div>
 </div>

<!-- <div class="btn-group" role="group" aria-label="...">
     <button type="button" class="btn btn-default">Left</button>
     <button type="button" class="btn btn-default">Middle</button>
     <button type="button" class="btn btn-default">Right</button>
 </div>-->
<!-- <p>
     <a href=" <?php //echo $this->url('album', array('action'=>'add'));?>">Add new album</a>
 </p>-->

 <table class="table">
 <tr>
     <th>Title</th>
     <th>Artist</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($albums as $album) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($album->autor);?></td>
     <td><?php echo $this->escapeHtml($album->nazwa);?></td>
     <td>
         <a href="<?php echo $this->url('album',
             array('action'=>'edit', 'id' => $album->id));?>">Edit</a>
         <a href="<?php echo $this->url('album',
             array('action'=>'delete', 'id' => $album->id));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>